# pi modifier key warning (don't know what this means , need to get back to this)
set -g extended-keys on

# fixing the j and k for traversal in the copy mode in tmux 
set-window-option -g mode-keys vi

# using vim motions to navigate between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# decreasing the waiting delay of tmux 
set -g repeat-time 200
